### ISSUE TITLE
CustomInput 훅에 기능 더 추가해도 되나요?

### ISSUE THREAD

**Issue by arkk200** [gimhanul/Gati-app#51]
### ❓ Question

https://www.codedaily.io/tutorials/Focus-on-the-Next-TextInput-when-Next-Keyboard-Button-is-Pressed-in-React-Native
이 기능을 넣으려고 하는데 feat/LoginPage 브랜치에서 추가하고 같이 push하면 될까요?

**Comment by gimhanul** [comment]
gogo
