### ISSUE TITLE
feat/profile에 프로필 페이지 만들어서 올렸는데 안되는 부분이 있어요

### ISSUE THREAD

**Issue by arkk200** [gimhanul/Gati-app#74]
### ❓ Question

ProfileEdit 스크린에서 KeyboardAvoidingView를 써서 키패드에 비밀번호 입력창이 가리는 걸 막을려고 했는데 작동이 안돼요

**Comment by gimhanul** [comment]
@SEOKKAMONI 너 써보지 않았냐
난 안 써봤ㄴ는디

**Comment by SEOKKAMONI** [comment]
일단 작업하고 있으면 저가 이따가 해결해보겠습니다
